### ISSUE TITLE
Recording failed on iOS

### ISSUE THREAD

**Issue by leon-jakob-schneider** [theolm/kmp-record#1]
Here are the logs:
AddInstanceForFactory: No factory registered for id <CFUUID 0x6000002f4060> F8BB1C28-BAE8-11D6-9C31-00039315CD46
     AudioQueueObject.cpp:1580  BuildConverter: AudioConverterNew returned -50
 from:  0 ch,  44100 Hz, .... (0x00000000) 0 bits/channel, 0 bytes/packet, 0 frames/packet, 0 bytes/frame
to:    1 ch,  44100 Hz, aac  (0x00000000) 0 bits/channel, 0 bytes/packet, 1024 frames/packet, 0 bytes/frame
     AudioQueueObject.cpp:6708  ConvertInput: aq@0x1088e8200: AudioConverterFillComplexBuffer returned -50, packetCount 21
Uncaught Kotlin exception: dev.theolm.record.error.RecordFailException: Could not record audio

I will do some more debugging when I have more time.

**Comment by theolm** [comment]
I have the same error on the simulator.
It works on a physical device. Even though I found information saying otherwise, I suspect that the ios simulator does not support mic recording. 

please try to build/run on a device.

**Comment by leon-jakob-schneider** [comment]
Also crashes on real device:
<img width="510" alt="Screenshot 2024-09-18 at 11 58 10" src="https://github.com/user-attachments/assets/7a81fb32-79a1-4213-a8c0-e14b4f11a2e9">

**Comment by mrljdx** [comment]
I had a similar problem and added a retry method to startRecording to fix it

**Comment by mrljdx** [comment]
@theolm @leon-jakob-schneider The question I recently settled, you can take a look at this PR [https://github.com/theolm/kmp-record/pull/3](https://github.com/theolm/kmp-record/pull/3) Wait for Maintainer to merge the request

**Comment by theolm** [comment]
@mrljdx Thanks for fixing this issue. Feel free to open more PRs... Unfortunately, I don't have enough time to dedicate to this lib =/

It will be available in the next release (I'll publish it asap)
